*creating the libname sq****;
libname sq '/home/PATH/ESQ1M6/data';


/**
	find out the states which have more population than the average population	
	***/
	
***	EXPLORING TABLES***;
PROC SQL OUTOBS=10;
	SELECT *
	FROM SQ.STATEPOPULATION;
QUIT;


PROC SQL NUMBER;
	SELECT NAME,
			POPESTIMATE1 FORMAT=COMMA16.
	FROM SQ.STATEPOPULATION
	WHERE POPESTIMATE1 > ( SELECT AVG(POPESTIMATE1)
							FROM SQ.STATEPOPULATION
							)
	ORDER BY POPESTIMATE1 DESC;
QUIT;


/***				ACTIVITY 2 - filtering the group data using having clause			***/
PROC SQL NUMBER;
	SELECT DIVISION, AVG(POPESTIMATE1) AS AVG_DIVISION_POP
			FROM SQ.STATEPOPULATION
			GROUP BY DIVISION
			HAVING AVG_DIVISION_POP > (
										SELECT AVG(POPESTIMATE1) AS AVERAGE_POPULATION
										FROM SQ.STATEPOPULATION
										);
QUIT;



/*************		SUBQUERY RETURNING MULTIPLE VALUES		****/
PROC SQL NUMBER;
	SELECT NAME
	FROM SQ.STATEPOPULATION 
	WHERE DIVISION = '3';
QUIT;


**** STATEMENTS USING SUBQUERY***;

PROC SQL OUTOBS=10 NUMBER;
	SELECT *
	FROM SQ.CUSTOMER
	WHERE STATE IN (
					SELECT NAME
					FROM SQ.STATEPOPULATION
					WHERE DIVISION = '3'
	);
QUIT;



/**************			SUBQUERY WITH ANY CLAUSE		****/

** COMPARISON OPERATOR	***;

PROC SQL NUMBER;
	SELECT NAME, POPESTIMATE1
	FROM SQ.STATEPOPULATION 
	WHERE POPESTIMATE1 > ANY(
								SELECT POPESTIMATE1
								FROM SQ.STATEPOPULATION 
								WHERE NAME IN ('NY', 'FL')
							);
QUIT;



PROC SQL NUMBER;
	SELECT NAME, POPESTIMATE1
	FROM SQ.STATEPOPULATION 
	WHERE POPESTIMATE1 < (
								SELECT MAX(POPESTIMATE1)
								FROM SQ.STATEPOPULATION 
								WHERE NAME IN ('NY', 'FL')
							);
QUIT;


/*****************		PRACTICE LEVEL 1		*************/
/**	CACLUATE THE STATES WHICH HAVE PROJECTED POPULATION GROWTH 
MUCH MORE THAN THE ESTIMATED GROWTH OF POPULAITON
**/

***	EXPLORING TABLES;
PROC SQL OUTOBS=5 NUMBER;
		SELECT *
		FROM SQ.STATEPOPULATION;
QUIT;


********	CREATING A SUBQUERY		***;
PROC SQL OUTOBS=5 NUMBER;
	SELECT MEAN(NPOPCHG3) "ESTIMATED GROWTH" FORMAT=COMMA16.
	FROM SQ.STATEPOPULATION;
QUIT;


PROC SQL NUMBER;
TITLE1 "States with an estimated 3-Year Population Growth";
TITLE2 "Greater than the Overall Average";

	SELECT NAME, NPOPCHG3 "ESTIMATED GROWTH" FORMAT=COMMA16.
	FROM SQ.STATEPOPULATION 
	WHERE NPOPCHG3 > (
						SELECT MEAN(NPOPCHG3)
						FROM SQ.STATEPOPULATION
					)
	ORDER BY NPOPCHG3 DESC;
QUIT;

TITLE;

/*****************		PRACTICE LEVEL 2		*************/

PROC SQL OUTOBS=5 NUMBER;
	SELECT *
	FROM SQ.CUSTOMER;
QUIT;


PROC SQL OUTOBS=5 NUMBER;
	SELECT  CUSTOMERID, FIRSTNAME, LASTNAME,
			CREDITSCORE			
	FROM SQ.CUSTOMER
	WHERE CREDITSCORE > (
							SELECT sum(avg(CreditScore),(2*std(CreditScore))) "HIGHSCORE"
							FROM SQ.CUSTOMER
						)
	AND STATE='TX'
	ORDER BY CREDITSCORE DESC;
QUIT;












